export const typehashTypes = {
  TokenTransfer: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'tokenAddress', type: 'address' },
    { name: 'amount', type: 'uint256' },
  ],
  AcrossTransfer: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'originModule', type: 'address' },
    { name: 'originAccount', type: 'address' },
    { name: 'targetAccount', type: 'address' },
    { name: 'originChainId', type: 'uint64' },
    { name: 'initiateDeadline', type: 'uint32' },
    { name: 'maxFee', type: 'uint256' },
    { name: 'depositId', type: 'uint256' },
    { name: 'originTransfer', type: 'bytes32' },
    { name: 'targetTransfer', type: 'bytes32' },
  ],
  Execution: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'target', type: 'address' },
    { name: 'value', type: 'uint256' },
    { name: 'callData', type: 'bytes32' },
  ],
  SignedExecutions: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'executions', type: 'bytes32' },
  ],
  PackedUserOperation: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'sender', type: 'address' },
    { name: 'nonce', type: 'uint256' },
    { name: 'initCode', type: 'bytes32' },
    { name: 'callData', type: 'bytes32' },
    { name: 'accountGasLimits', type: 'bytes32' },
    { name: 'preVerificationGas', type: 'uint256' },
    { name: 'gasFees', type: 'bytes32' },
    { name: 'paymasterAndData', type: 'bytes32' },
    { name: 'signature', type: 'bytes32' },
  ],
  SignedIntentWithAuctionFee: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'auctionFee', type: 'uint256' },
    { name: 'signedIntent', type: 'bytes32' },
  ],
  Settlement: [
    { name: 'typehash', type: 'bytes32' },
    { name: 'orchestrator', type: 'address' },
    { name: 'recipient', type: 'address' },
    { name: 'settlementContract', type: 'address' },
    { name: 'targetChainId', type: 'uint64' },
    { name: 'fillDeadline', type: 'uint32' },
    { name: 'lastDepositId', type: 'uint256' },
  ],
}
